# Generated by Django 5.2 on 2025-07-08 03:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhPhanTich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cau_hinh', models.CharField(max_length=100)),
                ('phien_ban_mac_dinh', models.CharField(choices=[('v0', 'Phiên bản gốc'), ('v1', 'Phiên bản 1')], default='v1', max_length=10)),
                ('phuong_phap_mac_dinh', models.JSONField(default=list, help_text='Danh sách các phương pháp mặc định')),
                ('trong_so_mac_dinh', models.JSONField(default=dict, help_text='Trọng số cho các phương pháp')),
                ('tham_so_khac', models.JSONField(default=dict, help_text='Các tham số khác')),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True)),
                ('mo_ta', models.TextField(blank=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cấu hình phân tích',
                'verbose_name_plural': 'Cấu hình phân tích',
                'ordering': ['-thoi_gian_cap_nhat'],
            },
        ),
        migrations.CreateModel(
            name='MethodWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Ngày có hiệu lực')),
                ('method_name', models.CharField(max_length=50, verbose_name='Tên phương pháp')),
                ('method_version', models.CharField(default='1.0', max_length=10, verbose_name='Phiên bản phương pháp')),
                ('phien_ban', models.CharField(choices=[('v0', 'Phiên bản gốc'), ('v1', 'Phiên bản 1')], default='v1', max_length=10)),
                ('weight', models.FloatField(verbose_name='Trọng số')),
                ('calculation_basis', models.CharField(choices=[('optimized', 'Tối ưu hóa tự động'), ('manual', 'Thiết lập thủ công'), ('historical', 'Dựa trên dữ liệu lịch sử')], default='optimized', max_length=20, verbose_name='Cơ sở tính toán')),
                ('days_analyzed', models.IntegerField(default=30, verbose_name='Số ngày phân tích')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Trọng số phương pháp',
                'verbose_name_plural': 'Trọng số các phương pháp',
                'ordering': ['-effective_date', 'method_name'],
                'unique_together': {('effective_date', 'method_name', 'method_version', 'phien_ban')},
            },
        ),
        migrations.CreateModel(
            name='QuyLuatBacNho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_quy_luat', models.CharField(help_text='Loại quy luật (theo ngày, theo thứ, ...)', max_length=50)),
                ('mo_ta', models.TextField(help_text='Mô tả quy luật')),
                ('phien_ban', models.CharField(choices=[('v0', 'Phiên bản gốc'), ('v1', 'Phiên bản 1')], default='v1', max_length=10)),
                ('dieu_kien', models.TextField(help_text='Điều kiện áp dụng quy luật (JSON)')),
                ('ket_qua', models.TextField(help_text='Kết quả dự đoán khi thỏa điều kiện (JSON)')),
                ('so_lan_ap_dung', models.IntegerField(default=0, help_text='Số lần áp dụng quy luật')),
                ('so_lan_trung', models.IntegerField(default=0, help_text='Số lần trúng khi áp dụng')),
                ('ty_le_trung', models.FloatField(default=0, help_text='Tỷ lệ trúng (%)')),
                ('ngay_phat_hien', models.DateField(default=django.utils.timezone.now, help_text='Ngày phát hiện quy luật')),
                ('co_hieu_luc', models.BooleanField(default=True, help_text='Quy luật còn hiệu lực không')),
                ('he_so_tin_cay', models.FloatField(default=50, help_text='Hệ số tin cậy (0-100%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quy luật bạc nhớ',
                'verbose_name_plural': 'Các quy luật bạc nhớ',
                'indexes': [models.Index(fields=['loai_quy_luat'], name='soicaubacnh_loai_qu_33d1c6_idx'), models.Index(fields=['co_hieu_luc'], name='soicaubacnh_co_hieu_e5ecda_idx'), models.Index(fields=['he_so_tin_cay'], name='soicaubacnh_he_so_t_e3f870_idx'), models.Index(fields=['phien_ban'], name='soicaubacnh_phien_b_93e47f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoiCauBacNho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phien_ban', models.CharField(choices=[('v0', 'Phiên bản gốc'), ('v1', 'Phiên bản 1')], default='v0', max_length=10, verbose_name='Phiên bản')),
                ('ngay_du_doan', models.DateField(help_text='Ngày dự đoán (target)')),
                ('ngay_phan_tich', models.DateField(default=django.utils.timezone.now, help_text='Ngày thực hiện phân tích')),
                ('phuong_phap', models.CharField(choices=[('theo_ngay', 'Soi cầu theo ngày'), ('theo_tong_db', 'Soi cầu theo tổng giải đặc biệt'), ('theo_thu', 'Soi cầu theo thứ'), ('theo_cap_kem', 'Soi cầu theo cặp số đi kèm'), ('theo_lo', 'Soi cầu theo lô'), ('theo_dau_cam', 'Soi cầu theo đầu câm'), ('theo_duoi_cam', 'Soi cầu theo đuôi câm'), ('discovered_rules', 'Quy luật đã phát hiện'), ('cyclical', 'Chu kỳ'), ('machine_learning', 'Học máy'), ('theo_dau_duoi_cam', 'Soi cầu theo đầu đuôi câm'), ('theo_kep', 'Soi cầu theo kép'), ('ml_advanced', 'Học máy nâng cao'), ('ensemble', 'Ensemble'), ('market_trend', 'Xu hướng thị trường'), ('ket_hop', 'Soi cầu kết hợp')], help_text='Phương pháp soi cầu', max_length=20)),
                ('ket_qua_ngay_truoc', models.CharField(help_text='Kết quả ngày trước đó', max_length=255)),
                ('thu_trong_tuan', models.IntegerField(help_text='Thứ trong tuần (0: Thứ Hai - 6: Chủ Nhật)')),
                ('ket_qua_du_doan', models.CharField(help_text='Kết quả dự đoán (dạng JSON)', max_length=255)),
                ('ty_le_tin_cay', models.FloatField(default=0, help_text='Tỷ lệ tin cậy của dự đoán (0-100%)')),
                ('ket_qua_thuc_te', models.CharField(blank=True, help_text='Kết quả thực tế', max_length=255, null=True)),
                ('ket_qua_trung', models.BooleanField(blank=True, help_text='Kết quả dự đoán có trúng không', null=True)),
                ('ghi_chu', models.TextField(blank=True, help_text='Ghi chú bổ sung', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soi cầu bạc nhớ',
                'verbose_name_plural': 'Soi cầu bạc nhớ',
                'indexes': [models.Index(fields=['ngay_du_doan'], name='soicaubacnh_ngay_du_6c9f0b_idx'), models.Index(fields=['phuong_phap'], name='soicaubacnh_phuong__ada8a4_idx'), models.Index(fields=['thu_trong_tuan'], name='soicaubacnh_thu_tro_418306_idx'), models.Index(fields=['phien_ban'], name='soicaubacnh_phien_b_0245cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhanTich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buoc_phan_tich', models.CharField(help_text='Tên bước phân tích', max_length=100)),
                ('thoi_gian_bat_dau', models.DateTimeField()),
                ('thoi_gian_ket_thuc', models.DateTimeField()),
                ('trang_thai', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại'), ('partial', 'Một phần')], max_length=20)),
                ('ket_qua', models.TextField(help_text='Kết quả chi tiết dạng JSON')),
                ('loi', models.TextField(blank=True, help_text='Thông tin lỗi nếu có', null=True)),
                ('soi_cau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='soicaubacnho.soicaubacnho')),
            ],
            options={
                'verbose_name': 'Chi tiết phân tích',
                'verbose_name_plural': 'Chi tiết phân tích',
                'ordering': ['soi_cau', 'thoi_gian_bat_dau'],
            },
        ),
        migrations.CreateModel(
            name='ThongKeHieuQua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong_phap', models.CharField(choices=[('theo_ngay', 'Soi cầu theo ngày'), ('theo_tong_db', 'Soi cầu theo tổng giải đặc biệt'), ('theo_thu', 'Soi cầu theo thứ'), ('theo_cap_kem', 'Soi cầu theo cặp số đi kèm'), ('theo_lo', 'Soi cầu theo lô'), ('theo_dau_cam', 'Soi cầu theo đầu câm'), ('theo_duoi_cam', 'Soi cầu theo đuôi câm'), ('discovered_rules', 'Quy luật đã phát hiện'), ('cyclical', 'Chu kỳ'), ('machine_learning', 'Học máy'), ('theo_dau_duoi_cam', 'Soi cầu theo đầu đuôi câm'), ('theo_kep', 'Soi cầu theo kép'), ('ml_advanced', 'Học máy nâng cao'), ('ensemble', 'Ensemble'), ('market_trend', 'Xu hướng thị trường'), ('ket_hop', 'Soi cầu kết hợp')], max_length=20)),
                ('ngay_bat_dau', models.DateField(help_text='Ngày bắt đầu thống kê')),
                ('ngay_ket_thuc', models.DateField(help_text='Ngày kết thúc thống kê')),
                ('phien_ban', models.CharField(choices=[('v0', 'Phiên bản gốc'), ('v1', 'Phiên bản 1')], default='v1', max_length=10)),
                ('tong_so_du_doan', models.IntegerField(default=0, help_text='Tổng số dự đoán')),
                ('so_lan_trung', models.IntegerField(default=0, help_text='Số lần trúng')),
                ('ty_le_trung', models.FloatField(default=0, help_text='Tỷ lệ trúng (%)')),
                ('du_doan_theo_ngay', models.TextField(blank=True, help_text='Chi tiết dự đoán theo ngày (JSON)')),
                ('xu_huong', models.CharField(choices=[('up', 'Tăng'), ('down', 'Giảm'), ('stable', 'Ổn định')], default='stable', max_length=20)),
                ('do_manh_xu_huong', models.FloatField(default=0, help_text='Độ mạnh của xu hướng (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thống kê hiệu quả',
                'verbose_name_plural': 'Thống kê hiệu quả',
                'indexes': [models.Index(fields=['phuong_phap'], name='soicaubacnh_phuong__dd2ac0_idx'), models.Index(fields=['ngay_bat_dau', 'ngay_ket_thuc'], name='soicaubacnh_ngay_ba_55e118_idx'), models.Index(fields=['phien_ban'], name='soicaubacnh_phien_b_f262bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='LichSuSoiCau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now)),
                ('doi_tuong_id', models.IntegerField(blank=True, null=True, verbose_name='ID đối tượng')),
                ('loai_soi_cau', models.CharField(max_length=50)),
                ('ket_qua', models.TextField(verbose_name='Kết quả JSON')),
                ('phien_ban', models.CharField(choices=[('v0', 'Phiên bản gốc'), ('v1', 'Phiên bản 1')], default='v1', max_length=10)),
                ('trang_thai', models.CharField(choices=[('chua_kiem_tra', 'Chưa kiểm tra'), ('trung', 'Trúng'), ('truot', 'Trượt')], default='chua_kiem_tra', max_length=20)),
                ('soi_cau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='soicaubacnho.soicaubacnho')),
            ],
            options={
                'verbose_name': 'Lịch sử soi cầu',
                'verbose_name_plural': 'Lịch sử soi cầu',
                'indexes': [models.Index(fields=['thoi_gian'], name='soicaubacnh_thoi_gi_f3925b_idx'), models.Index(fields=['phien_ban'], name='soicaubacnh_phien_b_5f515a_idx'), models.Index(fields=['trang_thai'], name='soicaubacnh_trang_t_eec8d0_idx')],
            },
        ),
    ]
